<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PageToMovie.Core\PageToMovie.Core.csproj" />
    <ProjectReference Include="..\PageToMovie.Fountain\PageToMovie.Fountain.csproj" />
    <ProjectReference Include="..\PageToMovie.Screenplay\PageToMovie.Screenplay.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\PageToMovie.Engine\MediaEngineEnums.cs" Link="MediaEngineEnums.cs" />
  </ItemGroup>

</Project>
