using System.Text;
using System.Text.RegularExpressions;
using PageToMovie.Core.Options;
using PageToMovie.Core.Utils;
using PageToMovie.Engine.Abstractions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace PageToMovie.Engine.ModelBacked;

/// <summary>
/// Rewrites a continuation clip's action so it says only what HAPPENS, dropping where things are.
/// </summary>
/// <remarks>
/// A continuation clip is generated by continuing the previous clip's last frame, so the model can
/// already see where everyone is. Stating a position in the action does not confirm that position —
/// it makes the model PLACE the subject there, and it re-places a subject that was already right.
/// Measured on Mary19 S02C02: the previous clip leaves the animal well down the aisle past the
/// middle of the desk rows, and the action reads "…the lamb standing small among the ink desk
/// legs", which is true of where it already is. The extend moved it back toward the front of the
/// room anyway. Remove the action and the same extend continues the motion correctly.
///
/// <para>This is why an instruction cannot fix it, and the "positions come from the previous frame"
/// sentence in the continuity block does not: the action is content, and content beats direction
/// for this model every time we have measured it. The only thing that works is not saying it.</para>
///
/// <para>Chat is preferred judgment for which words state a position — the next screenplay will
/// phrase it differently. A miss (chat off, beat_id absent, empty row) must still not ship a
/// restage, so <see cref="EventsOnly"/> always runs on clips that actually continue
/// (<c>veo_continuation_source</c> / extend_previous). Fresh / ForceNone / hard-cut clips keep
/// full staging. After the rewrite, place-restating <c>blocking_notes</c> are not appended;
/// body-facing / eyeline that is not a room restage may stay.</para>
/// </remarks>
public sealed class ContinuationActionClassifier : BeatChatClassifierBase<string>
{
    public const string PromptVersion = "v1_product";

    /// <summary>Beat field the extend/cut classifier writes; "extend" marks a continuation.</summary>
    private const string CutDecision = "cut_decision";
    private const string Extend = "extend";

    public ContinuationActionClassifier(
        IChatClient chat,
        IOptions<PageToMovieOptions> opts,
        ILogger<ContinuationActionClassifier> log,
        GenerationErrorLogger? errorLogger = null)
        : base(chat, opts.Value, log, errorLogger)
    {
    }

    protected override bool OptionEnabled => _opts.ClassifyContinuationActionWithChat;
    protected override string DefaultModel => _opts.ContinuationActionClassifyModel;
    protected override string? ChatMode => ChatCallModes.ContinuationActionClassify;
    protected override string OperationName => "stage2_continuation_action";
    protected override string ErrorLoggerName => "continuation_action_classifier";
    protected override string LogNoun => "continuation action";
    protected override string GetSystemPrompt() => SystemPrompt;
    protected override string BeatsHeading => "CONTINUATION BEATS TO REWRITE:";

    protected override string ProgressMessage(int beatCount) =>
        $"AI Continuity Editor: Rewriting {beatCount} continuation beat(s) to action only…";

    public const string SystemPrompt = """
        You prepare a shot's action line for a CONTINUATION clip.

        A continuation clip is generated by continuing the previous clip's LAST FRAME. Everything is
        already somewhere on screen and the model can see where. Saying where something is does not
        confirm it — it makes the model PLACE the subject there, and it will move a subject that was
        already in the right spot. So a position stated in the action moves things that must not move.

        For each beat, rewrite the action so it says only what HAPPENS.

        KEEP: every event, in the same order — who acts, what they do, how they do it, what they
        react to. Keep the original voice and wording wherever you can. Keep every Character_* token
        exactly as written.

        REMOVE: statements of where someone or something IS. Standing, sitting, lying or waiting
        somewhere; a positional phrase hung on a subject that is not the one acting; a restatement of
        the setting or of who is where.

        Do not add anything. Do not change who acts, or invent a new event. If a beat's action states
        no position at all, return it unchanged.

        Return ONLY valid JSON. Put the events in "action" and the placement you took out in
        "staging" — staging has a home in the reply, so it never has to stay in the action:
        {"actions":[{"beat_id":"b1","action":"...","staging":"..."}]}
        """;

    /// <summary>
    /// Only continuation beats are sent. A beat the extend/cut classifier called a hard cut is a
    /// fresh shot and needs its placement — staging is what a fresh shot is for.
    /// </summary>
    public static List<Dictionary<string, object?>> ContinuationBeats(
        IEnumerable<Dictionary<string, object?>> beats) =>
        beats.Where(IsContinuation).ToList();

    private static bool IsContinuation(Dictionary<string, object?> beat) =>
        string.Equals(
            beat.GetValueOrDefault(CutDecision)?.ToString()?.Trim(), Extend, StringComparison.OrdinalIgnoreCase);

    /// <summary>Participles that state a pose rather than an event.</summary>
    private static readonly string[] StativeWords =
        ["standing", "sitting", "lying", "waiting", "perched", "crouched", "kneeling", "seated"];

    /// <summary>Prepositions that place a body in the room.</summary>
    private static readonly string[] PlaceWords =
        ["among", "amid", "amidst", "beside", "behind", "between", "under", "against", "along",
         "near", "inside", "outside", "atop", "across", "front", "back", "left", "right"];

    private static readonly string[] BodyFacingWords =
        ["face", "faces", "facing", "eyeline", "looks", "look", "turns", "turn", "camera"];

    private static readonly char[] SentenceEnders = ['.', '!', '?'];
    private static readonly char[] ClauseEnders = [',', ';', ':'];
    private static readonly char[] WordTrim = ['.', ',', ';', ':', '!', '?', '-', '(', ')', '"'];

    /// <summary>
    /// Events-only Action for a continuation clip, used only when the classifier had no row for
    /// the beat. Two shapes go, both decided without parsing grammar: a sentence that
    /// <em>opens</em> with a pose in a place and then continues ("Standing small among the ink
    /// desk legs, Mary looks up."), and a short pose-in-place phrase <em>trailing</em> a sentence
    /// that already said something ("...clap at the lamb standing small among the ink desk legs").
    /// A trailing phrase carrying a conjunction is left alone, because that is where an event
    /// hides: "Nick is sitting behind the desk and slams the drawer shut" keeps its drawer.
    /// Anything else stays as written and the Continuity block does the work at generate time.
    /// </summary>
    public static string EventsOnly(string? action)
    {
        var text = action ?? "";
        if (string.IsNullOrWhiteSpace(text))
            return "";

        var rebuilt = new StringBuilder();
        foreach (var (sentence, ending) in SplitSentences(text))
        {
            rebuilt.Append(WithoutStaging(sentence).Trim()).Append(ending);
        }

        return CommonRegex.WhitespaceCollapse.Replace(rebuilt.ToString(), " ").Trim();
    }

    private static string WithoutStaging(string sentence)
    {
        var cut = sentence.IndexOfAny(ClauseEnders);
        if (cut >= 0 && !string.IsNullOrWhiteSpace(sentence[(cut + 1)..]) && IsPoseInAPlace(sentence[..cut]))
            return sentence[(cut + 1)..];
        return WithoutTrailingStaging(sentence);
    }

    /// <summary>
    /// A pose-in-place phrase hung on the end of a sentence that already said something. Bounded
    /// hard: it must start with a pose word, name a place, run to the sentence end, stay short,
    /// and carry no conjunction — a conjunction is where the event would be.
    /// </summary>
    private static string WithoutTrailingStaging(string sentence)
    {
        var words = sentence.Split(' ', StringSplitOptions.None);
        for (var i = 1; i < words.Length; i++)
        {
            var word = words[i].Trim(WordTrim);
            if (!StativeWords.Contains(word, StringComparer.OrdinalIgnoreCase))
                continue;
            var tail = words[i..];
            if (tail.Length > MaxTrailingStagingWords)
                continue;
            if (!tail.Any(w => PlaceWords.Contains(w.Trim(WordTrim), StringComparer.OrdinalIgnoreCase)))
                continue;
            if (tail.Any(w => Conjunctions.Contains(w.Trim(WordTrim), StringComparer.OrdinalIgnoreCase)))
                continue;
            return string.Join(' ', words[..i]);
        }
        return sentence;
    }

    private const int MaxTrailingStagingWords = 8;

    /// <summary>Where an event hides in a trailing phrase, so its presence calls the cut off.</summary>
    private static readonly string[] Conjunctions =
        ["and", "but", "then", "as", "while", "before", "after", "when", "until", "so"];

    /// <summary>Opens with a pose word and names a place: "Standing small among the desk legs".</summary>
    private static bool IsPoseInAPlace(string clause)
    {
        var words = Words(clause);
        if (words.Count == 0)
            return false;
        return StativeWords.Contains(words[0], StringComparer.OrdinalIgnoreCase)
               && words.Any(w => PlaceWords.Contains(w, StringComparer.OrdinalIgnoreCase));
    }

    /// <summary>Sentences with the punctuation that ended each one, so the prose rejoins as written.</summary>
    private static List<(string Sentence, string Ending)> SplitSentences(string text) =>
        SplitOn(text, SentenceEnders);

    /// <summary>
    /// Walk the text once. Drive the index in one place so a punctuation run stays on the
    /// current part and the next start is the character after the run.
    /// </summary>
    private static List<(string Text, string Ending)> SplitOn(string text, char[] enders)
    {
        var parts = new List<(string, string)>();
        var start = 0;
        var i = 0;
        while (i < text.Length)
        {
            if (!enders.Contains(text[i]))
            {
                i++;
                continue;
            }

            var stop = i;
            while (stop + 1 < text.Length && enders.Contains(text[stop + 1]))
                stop++;
            parts.Add((text[start..i], text[i..(stop + 1)] + " "));
            start = stop + 1;
            i = start;
        }

        if (start < text.Length)
            parts.Add((text[start..], ""));
        return parts;
    }

    /// <summary>
    /// Body-facing / eyeline that is not a room restage may ride on an extend. When in doubt,
    /// treat the note as place and drop it — a teleport is worse than a missing eyeline.
    /// </summary>
    public static bool IsBodyFacingOnly(string? notes)
    {
        var words = Words(notes ?? "");
        if (words.Count == 0)
            return false;
        if (words.Any(w => StativeWords.Contains(w, StringComparer.OrdinalIgnoreCase)
                           || PlaceWords.Contains(w, StringComparer.OrdinalIgnoreCase)))
            return false;
        return words.Any(w => BodyFacingWords.Contains(w, StringComparer.OrdinalIgnoreCase));
    }

    private static List<string> Words(string text) =>
        text.Split(' ', StringSplitOptions.RemoveEmptyEntries)
            .Select(w => w.Trim(WordTrim))
            .Where(w => w.Length > 0)
            .ToList();

    /// <summary>Clauses with the punctuation that ended each one, so the prose rejoins cleanly.</summary>
    private static List<(string Clause, string Separator)> SplitClauses(string text) =>
        SplitOn(text, ClauseEnders);

    public Task<Dictionary<string, string>?> ClassifySceneContinuationActionsAsync(
        Dictionary<string, object?> scene,
        List<Dictionary<string, object?>> beats,
        Action<string>? onProgress = null,
        CancellationToken ct = default,
        string? model = null) =>
        ClassifyAsync(scene, ContinuationBeats(beats), onProgress, ct, model);

    protected override void AppendBeat(StringBuilder sb, Dictionary<string, object?> b)
    {
        var (id, action, _, _) = ReadBeatCore(b);
        sb.AppendLine($"Beat '{id}':");
        AppendActionProse(sb, action);
    }

    protected override Dictionary<string, string>? ParseResponse(string rawJson) =>
        ClassifierDirectiveJson.ParseKeyedArray(
            rawJson,
            "actions",
            item =>
            {
                if (!item.TryGetProperty("beat_id", out var idEl) ||
                    !item.TryGetProperty("action", out var actionEl))
                    return null;
                var id = idEl.GetString();
                var action = actionEl.GetString();
                return string.IsNullOrWhiteSpace(id) || string.IsNullOrWhiteSpace(action)
                    ? null
                    : ((string? Id, string Value)?)(id, action.Trim());
            },
            _log,
            "continuation action");
}
