using System.Text;
using System.Text.RegularExpressions;
using PageToMovie.Core.Options;
using PageToMovie.Core.Utils;
using PageToMovie.Engine.Abstractions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace PageToMovie.Engine.ModelBacked;

/// <summary>
/// Rewrites a continuation clip's action so it says only what HAPPENS, dropping where things are.
/// </summary>
/// <remarks>
/// A continuation clip is generated by continuing the previous clip's last frame, so the model can
/// already see where everyone is. Stating a position in the action does not confirm that position —
/// it makes the model PLACE the subject there, and it re-places a subject that was already right.
/// Measured on Mary19 S02C02: the previous clip leaves the animal well down the aisle past the
/// middle of the desk rows, and the action reads "…the lamb standing small among the ink desk
/// legs", which is true of where it already is. The extend moved it back toward the front of the
/// room anyway. Remove the action and the same extend continues the motion correctly.
///
/// <para>This is why an instruction cannot fix it, and the "positions come from the previous frame"
/// sentence in the continuity block does not: the action is content, and content beats direction
/// for this model every time we have measured it. The only thing that works is not saying it.</para>
///
/// <para>Chat is preferred judgment for which words state a position — the next screenplay will
/// phrase it differently. A miss (chat off, beat_id absent, empty row) must still not ship a
/// restage, so <see cref="EventsOnly"/> always runs on clips that actually continue
/// (<c>veo_continuation_source</c> / extend_previous). Fresh / ForceNone / hard-cut clips keep
/// full staging. After the rewrite, place-restating <c>blocking_notes</c> are not appended;
/// body-facing / eyeline that is not a room restage may stay.</para>
/// </remarks>
public sealed class ContinuationActionClassifier : BeatChatClassifierBase<string>
{
    public const string PromptVersion = "v1_product";

    /// <summary>Beat field the extend/cut classifier writes; "extend" marks a continuation.</summary>
    private const string CutDecision = "cut_decision";
    private const string Extend = "extend";

    public ContinuationActionClassifier(
        IChatClient chat,
        IOptions<PageToMovieOptions> opts,
        ILogger<ContinuationActionClassifier> log,
        GenerationErrorLogger? errorLogger = null)
        : base(chat, opts.Value, log, errorLogger)
    {
    }

    protected override bool OptionEnabled => _opts.ClassifyContinuationActionWithChat;
    protected override string DefaultModel => _opts.ContinuationActionClassifyModel;
    protected override string? ChatMode => ChatCallModes.ContinuationActionClassify;
    protected override string OperationName => "stage2_continuation_action";
    protected override string ErrorLoggerName => "continuation_action_classifier";
    protected override string LogNoun => "continuation action";
    protected override string GetSystemPrompt() => SystemPrompt;
    protected override string BeatsHeading => "CONTINUATION BEATS TO REWRITE:";

    protected override string ProgressMessage(int beatCount) =>
        $"AI Continuity Editor: Rewriting {beatCount} continuation beat(s) to action only…";

    public const string SystemPrompt = """
        You prepare a shot's action line for a CONTINUATION clip.

        A continuation clip is generated by continuing the previous clip's LAST FRAME. Everything is
        already somewhere on screen and the model can see where. Saying where something is does not
        confirm it — it makes the model PLACE the subject there, and it will move a subject that was
        already in the right spot. So a position stated in the action moves things that must not move.

        For each beat, rewrite the action so it says only what HAPPENS.

        KEEP: every event, in the same order — who acts, what they do, how they do it, what they
        react to. Keep the original voice and wording wherever you can. Keep every Character_* token
        exactly as written.

        REMOVE: statements of where someone or something IS. Standing, sitting, lying or waiting
        somewhere; a positional phrase hung on a subject that is not the one acting; a restatement of
        the setting or of who is where.

        Do not add anything. Do not change who acts, or invent a new event. If a beat's action states
        no position at all, return it unchanged.

        Return ONLY valid JSON:
        {"actions":[{"beat_id":"b1","action":"..."}]}
        """;

    /// <summary>
    /// Only continuation beats are sent. A beat the extend/cut classifier called a hard cut is a
    /// fresh shot and needs its placement — staging is what a fresh shot is for.
    /// </summary>
    public static List<Dictionary<string, object?>> ContinuationBeats(
        IEnumerable<Dictionary<string, object?>> beats) =>
        beats.Where(IsContinuation).ToList();

    private static bool IsContinuation(Dictionary<string, object?> beat) =>
        string.Equals(
            beat.GetValueOrDefault(CutDecision)?.ToString()?.Trim(), Extend, StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Stative location clause: "standing small among the ink desk legs". The participle plus a
    /// place preposition is a PLACE, not an event — the measured teleport on extend.
    /// </summary>
    private static readonly Regex StativeLocationParticiple = new(
        @"\b(?:standing|sitting|lying|waiting|perched|crouched|kneeling)(?:\s+\w+){0,3}?\s+" +
        @"(?:among|amid(?:st)?|beside|behind|between|under|against|along|near|inside|outside|" +
        @"in\s+front\s+of|at\s+the)\b[^.,;:]*",
        RegexOptions.IgnoreCase | RegexOptions.Compiled,
        CommonRegex.Timeout);

    /// <summary>"is standing among the desks" — same restage, copula form.</summary>
    private static readonly Regex CopulaStativeLocation = new(
        @"\b(?:is|are|was|were)\s+(?:standing|sitting|lying|waiting)(?:\s+\w+){0,3}?\s+" +
        @"(?:among|amid(?:st)?|beside|behind|between|under|against|along|near|inside|outside|" +
        @"in\s+front\s+of|at\s+the)\b[^.,;:]*",
        RegexOptions.IgnoreCase | RegexOptions.Compiled,
        CommonRegex.Timeout);

    private static readonly Regex BodyFacing = new(
        @"\b(?:faces?|facing|eyeline|looks?\s+towards?|turns?\s+towards?|" +
        @"back\s+to\s+(?:the\s+)?camera|never\s+faces)\b",
        RegexOptions.IgnoreCase | RegexOptions.Compiled,
        CommonRegex.Timeout);

    private static readonly Regex PlaceRestage = new(
        @"\b(?:standing|sitting|lying|waiting|among|amid(?:st)?|beside|behind|between|" +
        @"under|against|along|near|inside|outside|in\s+front\s+of|" +
        @"at\s+the\s+(?:back|front)|across\s+the)\b",
        RegexOptions.IgnoreCase | RegexOptions.Compiled,
        CommonRegex.Timeout);

    private static readonly Regex SpaceBeforePunct = new(
        @"\s+([.,;:])", RegexOptions.Compiled, CommonRegex.Timeout);

    private static readonly Regex RepeatedPunct = new(
        @"([.,;:]){2,}", RegexOptions.Compiled, CommonRegex.Timeout);

    private static readonly Regex HangingPrep = new(
        @"\s+(?:at|to|toward|towards|of|from|among)\s*([.,;:]|$)",
        RegexOptions.IgnoreCase | RegexOptions.Compiled,
        CommonRegex.Timeout);

    /// <summary>
    /// Events-only Action for a clip that continues: keep what happens, drop where things are.
    /// Always applied on extend so a chat miss cannot ship a restage.
    /// </summary>
    public static string EventsOnly(string? action)
    {
        var text = action ?? "";
        if (string.IsNullOrWhiteSpace(text))
            return "";

        text = StativeLocationParticiple.Replace(text, "");
        text = CopulaStativeLocation.Replace(text, "");
        return TidyProse(text);
    }

    /// <summary>
    /// Body-facing / eyeline that is not a room restage may ride on an extend. When in doubt,
    /// treat the note as place and drop it — a teleport is worse than a missing eyeline.
    /// </summary>
    public static bool IsBodyFacingOnly(string? notes)
    {
        var text = notes ?? "";
        if (string.IsNullOrWhiteSpace(text))
            return false;
        if (PlaceRestage.IsMatch(text))
            return false;
        return BodyFacing.IsMatch(text);
    }

    private static string TidyProse(string text)
    {
        text = CommonRegex.WhitespaceCollapse.Replace(text, " ");
        text = SpaceBeforePunct.Replace(text, "$1");
        text = RepeatedPunct.Replace(text, "$1");
        text = HangingPrep.Replace(text, "$1");
        text = CommonRegex.WhitespaceCollapse.Replace(text, " ");
        text = SpaceBeforePunct.Replace(text, "$1");
        text = CommonRegex.Replace(text, @"^[.,;:]+\s*", "");
        return text.Trim();
    }

    public Task<Dictionary<string, string>?> ClassifySceneContinuationActionsAsync(
        Dictionary<string, object?> scene,
        List<Dictionary<string, object?>> beats,
        Action<string>? onProgress = null,
        CancellationToken ct = default,
        string? model = null) =>
        ClassifyAsync(scene, ContinuationBeats(beats), onProgress, ct, model);

    protected override void AppendBeat(StringBuilder sb, Dictionary<string, object?> b)
    {
        var (id, action, _, _) = ReadBeatCore(b);
        sb.AppendLine($"Beat '{id}':");
        AppendActionProse(sb, action);
    }

    protected override Dictionary<string, string>? ParseResponse(string rawJson) =>
        ClassifierDirectiveJson.ParseKeyedArray(
            rawJson,
            "actions",
            item =>
            {
                if (!item.TryGetProperty("beat_id", out var idEl) ||
                    !item.TryGetProperty("action", out var actionEl))
                    return null;
                var id = idEl.GetString();
                var action = actionEl.GetString();
                return string.IsNullOrWhiteSpace(id) || string.IsNullOrWhiteSpace(action)
                    ? null
                    : ((string? Id, string Value)?)(id, action.Trim());
            },
            _log,
            "continuation action");
}
