using System.Text;
using PageToMovie.Core.Options;
using PageToMovie.Engine.Abstractions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace PageToMovie.Engine.ModelBacked;

/// <summary>
/// Rewrites a continuation clip's action so it says only what HAPPENS, dropping where things are.
/// </summary>
/// <remarks>
/// A continuation clip is generated by continuing the previous clip's last frame, so the model can
/// already see where everyone is. Stating a position in the action does not confirm that position —
/// it makes the model PLACE the subject there, and it re-places a subject that was already right.
/// Measured on Mary19 S02C02: the previous clip leaves the animal well down the aisle past the
/// middle of the desk rows, and the action reads "…the lamb standing small among the ink desk
/// legs", which is true of where it already is. The extend moved it back toward the front of the
/// room anyway. Remove the action and the same extend continues the motion correctly.
///
/// <para>This is why an instruction cannot fix it, and the "positions come from the previous frame"
/// sentence in the continuity block does not: the action is content, and content beats direction
/// for this model every time we have measured it. The only thing that works is not saying it.</para>
///
/// <para>The rewrite is AI judgment rather than a phrase list, per AGENTS.md: which words state a
/// position is a question about language, not a fixed vocabulary, and the next screenplay will
/// phrase it differently. Only continuation clips are rewritten — a fresh clip needs its placement,
/// because staging the shot is exactly its job.</para>
/// </remarks>
public sealed class ContinuationActionClassifier : BeatChatClassifierBase<string>
{
    public const string PromptVersion = "v1_product";

    /// <summary>Beat field the extend/cut classifier writes; "extend" marks a continuation.</summary>
    private const string CutDecision = "cut_decision";
    private const string Extend = "extend";

    public ContinuationActionClassifier(
        IChatClient chat,
        IOptions<PageToMovieOptions> opts,
        ILogger<ContinuationActionClassifier> log,
        GenerationErrorLogger? errorLogger = null)
        : base(chat, opts.Value, log, errorLogger)
    {
    }

    protected override bool OptionEnabled => _opts.ClassifyContinuationActionWithChat;
    protected override string DefaultModel => _opts.ContinuationActionClassifyModel;
    protected override string? ChatMode => ChatCallModes.ContinuationActionClassify;
    protected override string OperationName => "stage2_continuation_action";
    protected override string ErrorLoggerName => "continuation_action_classifier";
    protected override string LogNoun => "continuation action";
    protected override string GetSystemPrompt() => SystemPrompt();
    protected override string BeatsHeading => "CONTINUATION BEATS TO REWRITE:";

    protected override string ProgressMessage(int beatCount) =>
        $"AI Continuity Editor: Rewriting {beatCount} continuation beat(s) to action only…";

    public static string SystemPrompt() => """
        You prepare a shot's action line for a CONTINUATION clip.

        A continuation clip is generated by continuing the previous clip's LAST FRAME. Everything is
        already somewhere on screen and the model can see where. Saying where something is does not
        confirm it — it makes the model PLACE the subject there, and it will move a subject that was
        already in the right spot. So a position stated in the action moves things that must not move.

        For each beat, rewrite the action so it says only what HAPPENS.

        KEEP: every event, in the same order — who acts, what they do, how they do it, what they
        react to. Keep the original voice and wording wherever you can. Keep every Character_* token
        exactly as written.

        REMOVE: statements of where someone or something IS. Standing, sitting, lying or waiting
        somewhere; a positional phrase hung on a subject that is not the one acting; a restatement of
        the setting or of who is where.

        Do not add anything. Do not change who acts, or invent a new event. If a beat's action states
        no position at all, return it unchanged.

        Return ONLY valid JSON:
        {"actions":[{"beat_id":"b1","action":"..."}]}
        """;

    /// <summary>
    /// Only continuation beats are sent. A beat the extend/cut classifier called a hard cut is a
    /// fresh shot and needs its placement — staging is what a fresh shot is for.
    /// </summary>
    public static List<Dictionary<string, object?>> ContinuationBeats(
        IEnumerable<Dictionary<string, object?>> beats) =>
        beats.Where(IsContinuation).ToList();

    private static bool IsContinuation(Dictionary<string, object?> beat) =>
        string.Equals(
            beat.GetValueOrDefault(CutDecision)?.ToString()?.Trim(), Extend, StringComparison.OrdinalIgnoreCase);

    public Task<Dictionary<string, string>?> ClassifySceneContinuationActionsAsync(
        Dictionary<string, object?> scene,
        List<Dictionary<string, object?>> beats,
        Action<string>? onProgress = null,
        CancellationToken ct = default,
        string? model = null) =>
        ClassifyAsync(scene, ContinuationBeats(beats), onProgress, ct, model);

    protected override void AppendBeat(StringBuilder sb, Dictionary<string, object?> b)
    {
        var (id, action, _, _) = ReadBeatCore(b);
        sb.AppendLine($"Beat '{id}':");
        AppendActionProse(sb, action);
    }

    protected override Dictionary<string, string>? ParseResponse(string rawJson) =>
        ClassifierDirectiveJson.ParseKeyedArray(
            rawJson,
            "actions",
            item =>
            {
                if (!item.TryGetProperty("beat_id", out var idEl) ||
                    !item.TryGetProperty("action", out var actionEl))
                    return null;
                var id = idEl.GetString();
                var action = actionEl.GetString();
                return string.IsNullOrWhiteSpace(id) || string.IsNullOrWhiteSpace(action)
                    ? null
                    : ((string? Id, string Value)?)(id, action.Trim());
            },
            _log,
            "continuation action");
}
