using PageToMovie.Core.Options;
using PageToMovie.Core.Utils;
using PageToMovie.Engine;
using PageToMovie.Engine.Abstractions;
using PageToMovie.Engine.ModelBacked;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Xunit;

namespace PageToMovie.Tests;

/// <summary>
/// A continuation clip is generated by continuing the previous clip's last frame, so the model can
/// already see where everyone is. Stating a position in the action does not confirm it — it makes
/// the model PLACE the subject there, and it re-places a subject that was already right.
/// </summary>
/// <remarks>
/// Measured on Mary19 S02C02: the previous clip leaves the animal well down the aisle past the
/// middle of the desk rows, and the action reads "…the lamb standing small among the ink desk legs",
/// which is true of where it already is. The extend moved it back toward the front of the room
/// anyway; removing the action entirely let the same extend continue correctly. An instruction
/// cannot fix that — the "positions come from the previous frame" line in the continuity block was
/// already there and lost. Only not saying it works.
/// </remarks>
public sealed class ContinuationActionTests
{
    private sealed class MockChat : IChatClient
    {
        public string Response { get; set; } = "";
        public List<string> Prompts { get; } = new();
        public bool IsConfigured => true;

        public Task<string> CompleteAsync(
            string systemPrompt, string userPrompt, string model = "grok-4.5",
            double temperature = 0.2, CancellationToken ct = default,
            string? mode = null, string? reasoningEffort = null)
        {
            Prompts.Add(userPrompt);
            return Task.FromResult(Response);
        }
    }

    private static Dictionary<string, object?> Beat(string id, string action, string cutDecision) => new()
    {
        ["beat_id"] = id,
        ["visual_event"] = action,
        ["cut_decision"] = cutDecision,
        ["primary_subject"] = "Character_The_Children",
    };

    // ---- which beats get rewritten -------------------------------------------------------------

    /// <summary>A fresh shot keeps its placement — staging the shot is exactly what it is for.</summary>
    [Fact]
    public void Only_continuation_beats_are_rewritten()
    {
        var beats = new List<Dictionary<string, object?>>
        {
            Beat("b1", "MARY comes through the door.", "hard_cut"),
            Beat("b2", "THE CHILDREN point at the lamb standing among the desk legs.", "extend"),
            Beat("b3", "TEACHER closes the book.", "extend"),
        };

        var selected = ContinuationActionClassifier.ContinuationBeats(beats);

        Assert.Equal(new[] { "b2", "b3" }, selected.Select(b => b["beat_id"]!.ToString()));
    }

    [Fact]
    public async Task A_scene_with_no_continuation_beats_makes_no_call()
    {
        var chat = new MockChat();
        var classifier = new ContinuationActionClassifier(
            chat,
            Options.Create(new PageToMovieOptions()),
            NullLogger<ContinuationActionClassifier>.Instance);

        var result = await classifier.ClassifySceneContinuationActionsAsync(
            new Dictionary<string, object?> { ["scene_number"] = 1 },
            new List<Dictionary<string, object?>> { Beat("b1", "MARY enters.", "hard_cut") });

        Assert.Null(result);
        Assert.Empty(chat.Prompts);
    }

    [Fact]
    public async Task Continuation_beats_are_sent_and_their_rewrites_parsed()
    {
        var chat = new MockChat
        {
            Response = """
                {"actions":[{"beat_id":"b2","action":"THE CHILDREN twist in their seats and point. They laugh and clap."}]}
                """,
        };
        var classifier = new ContinuationActionClassifier(
            chat,
            Options.Create(new PageToMovieOptions()),
            NullLogger<ContinuationActionClassifier>.Instance);

        var result = await classifier.ClassifySceneContinuationActionsAsync(
            new Dictionary<string, object?> { ["scene_number"] = 2 },
            new List<Dictionary<string, object?>>
            {
                Beat("b1", "MARY comes through the door.", "hard_cut"),
                Beat("b2", "THE CHILDREN twist and point at the lamb standing among the desk legs.", "extend"),
            });

        Assert.NotNull(result);
        Assert.Equal("THE CHILDREN twist in their seats and point. They laugh and clap.", result!["b2"]);
        // Only the continuation beat was described to the model.
        var asked = string.Join("\n", chat.Prompts);
        Assert.Contains("b2", asked, StringComparison.Ordinal);
        Assert.DoesNotContain("comes through the door", asked, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void The_prompt_says_why_a_stated_position_is_harmful()
    {
        var prompt = ContinuationActionClassifier.SystemPrompt;
        Assert.Contains("LAST FRAME", prompt, StringComparison.Ordinal);
        Assert.Contains("only what HAPPENS", prompt, StringComparison.Ordinal);
        Assert.Contains("where someone or something IS", prompt, StringComparison.Ordinal);
    }

    // ---- how the rewrite reaches the prompt ----------------------------------------------------

    private static string BuildPrompt(string beatAction, string? rewrite) =>
        Stage2PlannerService.BuildVisualPrompt(
            Beat("b2", beatAction, "extend"),
            new Dictionary<string, object?>
            {
                ["scene_number"] = 2,
                ["setting"] = "INT. SCHOOLROOM - DAY",
                ["characters_on_screen"] = new List<object?> { "Character_The_Children" },
            },
            new Dictionary<string, object?>(),
            new Dictionary<string, List<string>>(),
            rewrite);

    [Fact]
    public void The_rewritten_action_replaces_the_beats_own_action()
    {
        var prompt = BuildPrompt(
            "THE CHILDREN twist in their seats and point. They laugh and clap at the lamb standing small among the ink desk legs.",
            "THE CHILDREN twist in their seats and point. They laugh and clap.");

        Assert.Contains("twist in their seats", prompt, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("among the ink desk legs", prompt, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Without_a_rewrite_the_beats_own_action_is_used_unchanged()
    {
        var prompt = BuildPrompt(
            "THE CHILDREN twist in their seats and point. They laugh and clap at the lamb standing small among the ink desk legs.",
            null);

        Assert.Contains("among the ink desk legs", prompt, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// The rewrite goes through the same handling the beat's own action would: it lands in the
    /// Action tag, not appended raw, so cast keys, blocking notes and sound cues still apply.
    /// </summary>
    [Fact]
    public void The_rewrite_still_lands_in_the_action_tag()
    {
        var prompt = BuildPrompt(
            "THE CHILDREN point at the lamb standing among the desk legs.",
            "THE CHILDREN twist and point. (SOUND: children laughing)");

        Assert.Contains($"<{PromptFieldTags.Action}>", prompt, StringComparison.Ordinal);
        Assert.Contains("twist and point", prompt, StringComparison.OrdinalIgnoreCase);
        // Sound cues are still lifted out of the action into their own slot at plan time.
        Assert.DoesNotContain("(SOUND:", prompt, StringComparison.OrdinalIgnoreCase);
    }
}
