using PageToMovie.Core.Options;
using PageToMovie.Core.Utils;
using PageToMovie.Engine;
using PageToMovie.Engine.Abstractions;
using PageToMovie.Engine.ModelBacked;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Xunit;

namespace PageToMovie.Tests;

/// <summary>
/// A continuation clip is generated by continuing the previous clip's last frame, so the model can
/// already see where everyone is. Stating a position in the action does not confirm it — it makes
/// the model PLACE the subject there, and it re-places a subject that was already right.
/// </summary>
/// <remarks>
/// Measured on Mary19 S02C02: the previous clip leaves the animal well down the aisle past the
/// middle of the desk rows, and the action reads "…the lamb standing small among the ink desk legs",
/// which is true of where it already is. The extend moved it back toward the front of the room
/// anyway; removing the action entirely let the same extend continue correctly. An instruction
/// cannot fix that — the "positions come from the previous frame" line in the continuity block was
/// already there and lost. Only not saying it works.
/// </remarks>
public sealed class ContinuationActionTests
{
    private sealed class MockChat : IChatClient
    {
        public string Response { get; set; } = "";
        public List<string> Prompts { get; } = new();
        public bool IsConfigured => true;

        public Task<string> CompleteAsync(
            string systemPrompt, string userPrompt, string model = "grok-4.5",
            double temperature = 0.2, CancellationToken ct = default,
            string? mode = null, string? reasoningEffort = null)
        {
            Prompts.Add(userPrompt);
            return Task.FromResult(Response);
        }
    }

    private static Dictionary<string, object?> Beat(string id, string action, string cutDecision) => new()
    {
        ["beat_id"] = id,
        ["visual_event"] = action,
        ["cut_decision"] = cutDecision,
        ["primary_subject"] = "Character_The_Children",
    };

    // ---- which beats get rewritten -------------------------------------------------------------

    /// <summary>A fresh shot keeps its placement — staging the shot is exactly what it is for.</summary>
    [Fact]
    public void Only_continuation_beats_are_rewritten()
    {
        var beats = new List<Dictionary<string, object?>>
        {
            Beat("b1", "MARY comes through the door.", "hard_cut"),
            Beat("b2", "THE CHILDREN point at the lamb standing among the desk legs.", "extend"),
            Beat("b3", "TEACHER closes the book.", "extend"),
        };

        var selected = ContinuationActionClassifier.ContinuationBeats(beats);

        Assert.Equal(new[] { "b2", "b3" }, selected.Select(b => b["beat_id"]!.ToString()));
    }

    [Fact]
    public async Task A_scene_with_no_continuation_beats_makes_no_call()
    {
        var chat = new MockChat();
        var classifier = new ContinuationActionClassifier(
            chat,
            Options.Create(new PageToMovieOptions()),
            NullLogger<ContinuationActionClassifier>.Instance);

        var result = await classifier.ClassifySceneContinuationActionsAsync(
            new Dictionary<string, object?> { ["scene_number"] = 1 },
            new List<Dictionary<string, object?>> { Beat("b1", "MARY enters.", "hard_cut") });

        Assert.Null(result);
        Assert.Empty(chat.Prompts);
    }

    [Fact]
    public async Task Continuation_beats_are_sent_and_their_rewrites_parsed()
    {
        var chat = new MockChat
        {
            Response = """
                {"actions":[{"beat_id":"b2","action":"THE CHILDREN twist in their seats and point. They laugh and clap."}]}
                """,
        };
        var classifier = new ContinuationActionClassifier(
            chat,
            Options.Create(new PageToMovieOptions()),
            NullLogger<ContinuationActionClassifier>.Instance);

        var result = await classifier.ClassifySceneContinuationActionsAsync(
            new Dictionary<string, object?> { ["scene_number"] = 2 },
            new List<Dictionary<string, object?>>
            {
                Beat("b1", "MARY comes through the door.", "hard_cut"),
                Beat("b2", "THE CHILDREN twist and point at the lamb standing among the desk legs.", "extend"),
            });

        Assert.NotNull(result);
        Assert.Equal("THE CHILDREN twist in their seats and point. They laugh and clap.", result!["b2"]);
        // Only the continuation beat was described to the model.
        var asked = string.Join("\n", chat.Prompts);
        Assert.Contains("b2", asked, StringComparison.Ordinal);
        Assert.DoesNotContain("comes through the door", asked, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void The_prompt_says_why_a_stated_position_is_harmful()
    {
        var prompt = ContinuationActionClassifier.SystemPrompt;
        Assert.Contains("LAST FRAME", prompt, StringComparison.Ordinal);
        Assert.Contains("only what HAPPENS", prompt, StringComparison.Ordinal);
        Assert.Contains("where someone or something IS", prompt, StringComparison.Ordinal);
    }

    // ---- how the rewrite reaches the prompt ----------------------------------------------------

    private const string StandingAmongDesks =
        "THE CHILDREN twist in their seats and point. They laugh and clap at the lamb standing small among the ink desk legs.";

    private static string BuildPrompt(
        string beatAction,
        string? rewrite,
        bool isContinuation,
        string? blockingNotes = null)
    {
        var beat = Beat("b2", beatAction, isContinuation ? "extend" : "hard_cut");
        if (blockingNotes is not null)
            beat["blocking_notes"] = blockingNotes;
        return Stage2PlannerService.BuildVisualPrompt(
            beat,
            new Dictionary<string, object?>
            {
                ["scene_number"] = 2,
                ["setting"] = "INT. SCHOOLROOM - DAY",
                ["characters_on_screen"] = new List<object?> { "Character_The_Children" },
            },
            new Dictionary<string, object?>(),
            new Dictionary<string, List<string>>(),
            rewrite,
            isContinuation);
    }

    private static string ActionOf(string prompt) =>
        ClipPromptSections.Parse(prompt).First(s => s.Field == ClipPromptField.Action).Value;

    [Fact]
    public void The_rewritten_action_replaces_the_beats_own_action()
    {
        var action = ActionOf(BuildPrompt(
            StandingAmongDesks,
            "THE CHILDREN twist in their seats and point. They laugh and clap.",
            isContinuation: true));

        Assert.Contains("twist in their seats", action, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("laugh and clap", action, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("among the ink desk legs", action, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("standing", action, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Continuation_still_strips_placement_left_in_a_chat_rewrite()
    {
        var action = ActionOf(BuildPrompt(StandingAmongDesks, StandingAmongDesks, isContinuation: true));

        Assert.Contains("twist in their seats", action, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("among the ink desk legs", action, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Chat_miss_still_strips_placement_from_a_continuation_action()
    {
        var action = ActionOf(BuildPrompt(StandingAmongDesks, rewrite: null, isContinuation: true));

        Assert.Contains("twist in their seats", action, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("laugh and clap", action, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("among the ink desk legs", action, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("standing small", action, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Fresh_clip_keeps_placement()
    {
        var action = ActionOf(BuildPrompt(StandingAmongDesks, rewrite: null, isContinuation: false));

        Assert.Contains("among the ink desk legs", action, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("standing small", action, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Place_blocking_notes_are_not_reapplied_on_a_continuation()
    {
        var action = ActionOf(BuildPrompt(
            "THE CHILDREN twist in their seats and point. They laugh and clap.",
            "THE CHILDREN twist in their seats and point. They laugh and clap.",
            isContinuation: true,
            blockingNotes: "the lamb standing small among the ink desk legs"));

        Assert.Contains("twist in their seats", action, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("among the ink desk legs", action, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("standing", action, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Fresh_clip_still_receives_place_blocking_notes()
    {
        var action = ActionOf(BuildPrompt(
            "THE CHILDREN twist in their seats and point.",
            rewrite: null,
            isContinuation: false,
            blockingNotes: "the lamb standing small among the ink desk legs"));

        Assert.Contains("among the ink desk legs", action, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Body_facing_blocking_that_is_not_a_restage_may_stay_on_a_continuation()
    {
        var action = ActionOf(BuildPrompt(
            "THE CHILDREN twist in their seats and point.",
            "THE CHILDREN twist in their seats and point.",
            isContinuation: true,
            blockingNotes: "eyeline on the speaker; faces the window"));

        Assert.Contains("eyeline on the speaker", action, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("faces the window", action, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// The rewrite goes through the same handling the beat's own action would: it lands in the
    /// Action tag, not appended raw, so cast keys and sound cues still apply.
    /// </summary>
    [Fact]
    public void The_rewrite_still_lands_in_the_action_tag()
    {
        var prompt = BuildPrompt(
            "THE CHILDREN point at the lamb standing among the desk legs.",
            "THE CHILDREN twist and point. (SOUND: children laughing)",
            isContinuation: true);

        Assert.Contains($"<{PromptFieldTags.Action}>", prompt, StringComparison.Ordinal);
        Assert.Contains("twist and point", prompt, StringComparison.OrdinalIgnoreCase);
        // Sound cues are still lifted out of the action into their own slot at plan time.
        Assert.DoesNotContain("(SOUND:", prompt, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void EventsOnly_drops_the_standing_among_desks_clause_and_keeps_events()
    {
        var stripped = ContinuationActionClassifier.EventsOnly(StandingAmongDesks);

        Assert.Contains("twist in their seats", stripped, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("laugh and clap", stripped, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("among the ink desk legs", stripped, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("standing small", stripped, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void EventsOnly_leaves_action_with_no_place_clause_unchanged()
    {
        const string events = "THE CHILDREN twist in their seats and point. They laugh and clap.";
        Assert.Equal(events, ContinuationActionClassifier.EventsOnly(events));
    }
}
