using System.Text.Json;
using PageToMovie.Core.Options;
using PageToMovie.Engine;
using PageToMovie.Engine.Abstractions;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Xunit;

namespace PageToMovie.Tests;

/// <summary>
/// A continuation clip is generated by continuing the previous clip's last frame, so its action has
/// to open where the previous clip left the cast. Stage 2 used to write every clip's action from its
/// own screenplay beat with no idea what the beat before it left on screen, which handed the model a
/// &lt;Continuity&gt; block saying "pick up from the last frame" beside an &lt;Action&gt; describing
/// a different arrangement of the room. The model followed the Action and the subject jumped across
/// the set. These cover the three places that changed: the extend/cut prompt that now asks the
/// staging question, the rule stamp the plan carries so the check is visible, and the lint that
/// reads it.
/// </summary>
public sealed class ContinuationStagingTests : IDisposable
{
    private readonly string _root;
    private readonly ProjectStore _store;

    public ContinuationStagingTests()
    {
        _root = Path.Combine(Path.GetTempPath(), "fs-cont-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(Path.Combine(_root, "projects", "Demo"));
        _store = new ProjectStore(Options.Create(new PageToMovieOptions { WorkspaceRoot = _root }));
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_root))
                Directory.Delete(_root, recursive: true);
        }
        catch { /* ignore */ }
    }

    private sealed class OfflineChat : IChatClient
    {
        public bool IsConfigured => false;

        public Task<string> CompleteAsync(
            string systemPrompt, string userPrompt, string model = "grok-4.5",
            double temperature = 0.2, CancellationToken ct = default,
            string? mode = null, string? reasoningEffort = null) =>
            Task.FromResult("");
    }

    // ---- The shipped prompt asks the staging question ------------------------------------------

    [Fact]
    public void Shipped_extend_cut_prompt_asks_where_the_previous_beat_left_the_subjects()
    {
        var prompt = ExtendCutClassifier.SystemPrompt();
        Assert.Contains("last frame", prompt, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("staging is not where the previous", prompt, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("cannot teleport", prompt, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// The beat that caused this had every verb on one subject and the displaced subject only
    /// described standing somewhere new. A staging test that reads the acting subject alone finds
    /// nothing but continuous small motion and labels the pair extend — the original bug again.
    /// </summary>
    [Fact]
    public void Shipped_extend_cut_prompt_checks_described_subjects_not_only_acting_ones()
    {
        var prompt = ExtendCutClassifier.SystemPrompt();
        Assert.Contains("EVERY subject the beat names", prompt, StringComparison.Ordinal);
        Assert.Contains("not only the one doing something", prompt, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// The benchmark scores a prompt file, not the class — they only mean anything together. The
    /// shipped prompt sat at v1 while the eval corpus reached v3; this keeps them married.
    /// </summary>
    [Fact]
    public void Shipped_extend_cut_prompt_matches_its_benchmark_prompt_file()
    {
        var path = Path.Combine(
            FindHostRoot(), "evals", "classifier_benchmarks", "prompts", "extend_cut",
            ExtendCutClassifier.PromptVersion + ".txt");
        Assert.True(File.Exists(path), $"No benchmark prompt for the shipped version: {path}");
        Assert.Equal(
            Normalize(File.ReadAllText(path)),
            Normalize(ExtendCutClassifier.SystemPrompt()));
    }

    // ---- The plan records which rule decided each continuation ---------------------------------

    [Fact]
    public async Task Heuristic_only_extend_cut_stamps_every_beat_with_the_rule_that_decided_it()
    {
        var stage1 = Stage1WithTwoBeats();
        var classifier = new ExtendCutClassifier(
            new OfflineChat(),
            Options.Create(new PageToMovieOptions { ClassifyExtendCutWithChat = true }),
            NullLogger<ExtendCutClassifier>.Instance);

        var result = await classifier.ClassifyStage1Async(stage1);

        Assert.False(result.Enabled);
        foreach (var beat in BeatsOf(stage1))
        {
            Assert.True(beat.ContainsKey("cut_decision"));
            Assert.Equal(
                ExtendCutClassifier.HeuristicRule,
                beat[ExtendCutClassifier.CutDecisionRuleKey]?.ToString());
        }
    }

    /// <summary>
    /// The stamp has to reach the blueprint, not just the beat — ShotPlanLint and the clip list
    /// only ever see the planned clip.
    /// </summary>
    [Fact]
    public async Task Planned_clips_carry_the_continuity_rule_that_decided_them()
    {
        const string projectId = "Demo";
        await OfflineTestModelConfig.ApplyAsync(_store, projectId);
        ScreenplayService.SaveDraft(_store, projectId, """
            Title: Continuity Stamp

            INT. SCHOOLROOM - DAY

            A small animal waits at the door at the back of the room.

            TEACHER
            Wait outside, please.

            The children twist in their seats and point.
            """);
        var sign = ScreenplayService.SignOff(_store, projectId);
        Assert.True(sign.Ok, sign.Error);

        var planner = new Stage2PlannerService(_store, NullLogger<Stage2PlannerService>.Instance);
        var result = await planner.PlanAsync(projectId, resolution: "480p", scenes: "all");
        Assert.True(result.Ok);

        using var doc = JsonDocument.Parse(await File.ReadAllTextAsync(result.OutPath!));
        // The end-credits card is not planned from a beat and continues nothing, so it carries no
        // rule — and the lint never asks it for one (its continuation is "none").
        var clips = doc.RootElement.GetProperty("scenes").EnumerateArray()
            .SelectMany(s => s.GetProperty("veo_clips").EnumerateArray())
            .Where(c => !(c.TryGetProperty("is_credits", out var cr) && cr.ValueKind == JsonValueKind.True))
            .ToList();
        Assert.NotEmpty(clips);
        foreach (var clip in clips)
        {
            Assert.True(clip.TryGetProperty("continuity_rule", out var rule),
                "every planned clip records which rule decided its continuation");
            Assert.False(string.IsNullOrWhiteSpace(rule.GetString()));
        }
    }

    /// <summary>
    /// The refiner rewrites continuation from camera framing alone. A clip it turns INTO a
    /// continuation has not been staging-checked, so the inherited stamp has to go — otherwise the
    /// lint reports a checked continuation that nothing checked.
    /// </summary>
    [Theory]
    [InlineData("none", "extend_previous", false)]
    [InlineData("extend_previous", "extend_previous", true)]
    [InlineData("extend_previous", "none", true)]
    public void Refiner_keeps_the_stamp_only_where_it_still_describes_the_decision(
        string before, string after, bool stampSurvives)
    {
        var clip = new Dictionary<string, object?>
        {
            ["veo_continuation_source"] = before,
            ["continuity_rule"] = "v4_staging",
        };

        InvokeDropContinuityRule(clip, after);

        Assert.Equal(stampSurvives, clip.ContainsKey("continuity_rule"));
    }

    private static void InvokeDropContinuityRule(Dictionary<string, object?> clip, string continuation)
    {
        var m = typeof(ShotPlanRefiningClassifier).GetMethod(
            "DropContinuityRuleIfNewlyExtending",
            System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)
            ?? throw new InvalidOperationException("DropContinuityRuleIfNewlyExtending not found");
        m.Invoke(null, new object?[] { clip, continuation });
    }

    // ---- The lint reads the stamp --------------------------------------------------------------

    [Fact]
    public void Extend_clip_from_a_plan_with_no_continuity_rule_is_an_advisory_finding()
    {
        using var doc = JsonDocument.Parse(
            "{\"clip_number\":2,\"veo_continuation_source\":\"extend_previous\"," +
            "\"visual_prompt\":\"<Action>The children point.</Action>\"}");
        var f = Assert.Single(ShotPlanLint.Check(doc.RootElement, Array.Empty<string>()));
        Assert.Equal("continuation_unchecked", f.Rule);
        Assert.True(f.Advisory, "an old plan's extends are mostly fine — say so, do not stale them");
        Assert.Contains("rebuild the shot plan", f.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Extend_clip_whose_plan_records_the_rule_is_not_a_finding()
    {
        using var doc = JsonDocument.Parse(
            "{\"clip_number\":2,\"veo_continuation_source\":\"extend_previous\"," +
            "\"continuity_rule\":\"v4_staging\"," +
            "\"visual_prompt\":\"<Action>The children point.</Action>\"}");
        Assert.Empty(ShotPlanLint.Check(doc.RootElement, Array.Empty<string>()));
    }

    [Fact]
    public void Clip_that_does_not_continue_anything_needs_no_stamp()
    {
        using var doc = JsonDocument.Parse(
            "{\"clip_number\":1,\"veo_continuation_source\":\"none\"," +
            "\"visual_prompt\":\"<Action>The children point.</Action>\"}");
        Assert.Empty(ShotPlanLint.Check(doc.RootElement, Array.Empty<string>()));
    }

    // ---- helpers -------------------------------------------------------------------------------

    private static string Normalize(string text) => text.Replace("\r\n", "\n").Trim();

    private static string FindHostRoot()
    {
        var d = new DirectoryInfo(AppContext.BaseDirectory);
        while (d is not null)
        {
            if (Directory.Exists(Path.Combine(d.FullName, "evals", "classifier_benchmarks")))
                return d.FullName;
            d = d.Parent;
        }
        throw new DirectoryNotFoundException("Could not locate host/ from " + AppContext.BaseDirectory);
    }

    private static Dictionary<string, object?> Stage1WithTwoBeats() => new()
    {
        ["scenes"] = new List<object?>
        {
            new Dictionary<string, object?>
            {
                ["setting"] = "INT. SCHOOLROOM - DAY",
                ["primary_location_id"] = "Loc_Schoolroom",
                ["story_beats"] = new List<object?>
                {
                    new Dictionary<string, object?>
                    {
                        ["beat_id"] = "b1",
                        ["visual_event"] = "A small animal waits at the door at the back of the room.",
                        ["action_class"] = "small_motion",
                    },
                    new Dictionary<string, object?>
                    {
                        ["beat_id"] = "b2",
                        ["visual_event"] = "The children twist in their seats and point at the animal among the desk legs.",
                        ["action_class"] = "small_motion",
                    },
                },
            },
        },
    };

    private static IEnumerable<Dictionary<string, object?>> BeatsOf(Dictionary<string, object?> stage1) =>
        ((List<object?>)stage1["scenes"]!)
            .OfType<Dictionary<string, object?>>()
            .SelectMany(s => ((List<object?>)s["story_beats"]!).OfType<Dictionary<string, object?>>());
}
